### PR TITLE
updated sbt version, bumped npm dependencies (babel, when)

### PR DESCRIPTION
**Pull request by janwillemvd**

### CODE REVIEW

**Comment by janwillemvd** [comment]
updated sbt version, bumped npm dependencies (babel, when)

**Comment by zenato** [comment]
@janwillemvd Thank you for PR!! 👍

**Comment by janwillemvd** [comment]
@zenato no problem, thank you for merging so quickly! When do you think this will be published?

**Comment by zenato** [comment]
@janwillemvd Released v1.1.0!! 😄

**Comment by janwillemvd** [comment]
@zenato Awesome, thanks!!

**Pull request merged**
